version: v1.0.0
kind: CRS Application Attack XSS
rules:
  - id: 941100
    payload: |
      (?i).(?:\b(?:x(?:link:href|html|mlns)|data:text\/html|formaction|pattern\b.*?=)|!ENTITY[\s\v]+(?:%[\s\v]+)?[^\s\v]+[\s\v]+(?:SYSTEM|PUBLIC)|@import|;base64)\b
    matchType: regex
    action: deny
    placeholders:
      - URLFilename
      - URLParamName
      - URLParamValue
      - HeaderValue:User-Agent
      - RawBody
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941130
    payload: |
      (?i).(?:\b(?:x(?:link:href|html|mlns)|data:text\/html|formaction|pattern\b.*?=)|!ENTITY[\s\v]+(?:%[\s\v]+)?[^\s\v]+[\s\v]+(?:SYSTEM|PUBLIC)|@import|;base64)\b
    matchType: regex
    action: deny
    placeholders:
      - URLFilename
      - URLParamName
      - URLParamValue
      - HeaderValue:User-Agent
      - RawBody
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941160
    payload: |
      (?i).(?:\b(?:x(?:link:href|html|mlns)|data:text\/html|formaction|pattern\b.*?=)|!ENTITY[\s\v]+(?:%[\s\v]+)?[^\s\v]+[\s\v]+(?:SYSTEM|PUBLIC)|@import|;base64)\b
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
      - HeaderValue:User-Agent
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941170
    payload: |
      (?i)(?:\W|^)(?:javascript:(?:[\s\S]+[=\x5c\(\[\.<]|[\s\S]*?(?:\bname\b|\x5c[ux]\d))|data:(?:(?:[a-z]\w+\/\w[\w+-]+\w)?[;,]|[\s\S]*?;[\s\S]*?\b(?:base64|charset=)|[\s\S]*?,[\s\S]*?<[\s\S]*?\w[\s\S]*?>))|@\W*?i\W*?m\W*?p\W*?o\W*?r\W*?t\W*?(?:\/\*[\s\S]*?)?(?:[\"']|\W*?u\W*?r\W*?l[\s\S]*?\()|[^-]*?-\W*?m\W*?o\W*?z\W*?-\W*?b\W*?i\W*?n\W*?d\W*?i\W*?n\W*?g[^:]*?:\W*?u\W*?r\W*?l[\s\S]*?\(
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
      - HeaderValue:User-Agent
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941180
    payload: |
      document.cookie document.domain document.write .parentnode .innerhtml window.location -moz-binding <!-- <![cdata[
    matchType: multi-text
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941190
    payload: |
      (\?i:<style.*?>.*?(?:@[i\x5c]|(?:[:=]|&#x?0*(?:58|3A|61|3D);?).*?(?:[(\x5c]|&#x?0*(?:40|28|92|5C);?)))
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941210
    payload: |
      (?i)(?:j|&#(?:0*(?:74|106)|x0*[46]A);)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:a|&#(?:0*(?:65|97)|x0*[46]1);)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:v|&#(?:0*(?:86|118)|x0*[57]6);)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:a|&#(?:0*(?:65|97)|x0*[46]1);)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:s|&#(?:0*(?:115|83)|x0*[57]3);)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:c|&#(?:x0*[46]3|0*(?:99|67));)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:r|&#(?:x0*[57]2|0*(?:114|82));)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:i|&#(?:x0*[46]9|0*(?:105|73));)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:p|&#(?:x0*[57]0|0*(?:112|80));)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?:t|&#(?:x0*[57]4|0*(?:116|84));)(?:[\t-\n\r]|&(?:#(?:0*(?:9|1[03])|x0*[AD]);?|(?:tab|newline);))*(?::|&(?:#(?:0*58|x0*3A);?|colon;)).
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941280
    payload: |
      (?i)<BASE[\s/+].*?href[\s/+]*=
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941300
    payload: |
      (?i)<OBJECT[\s/+].*?(?:type|codetype|classid|code|data)[\s/+]*=
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941370
    payload: |
      (?:self|document|this|top|window)\s*(?:\/\*|[\[)]).+?(?:\]|\*\/)
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL
  - id: 941390
    payload: |
      (?i)\b(?:eval|set(?:timeout|interval)|new[\s\v]+Function|a(?:lert|tob)|btoa)[\s\v]*\(
    matchType: regex
    action: deny
    placeholders:
      - URLParamName
      - URLParamValue
      - RawBody
      - URLFilename
    transformations:
      - Base64
      - URL
      - Base64|URL